name: BIRD Tests

on:
  push:
    branches: [ "main", "test-framework" ]
  pull_request:
    branches: [ "main", "test-framework" ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      max-parallel: 4
      matrix:
        python-version: [3.13]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v3
      with:
        python-version: ${{ matrix.python-version }}
    - name: Setup and Run Tests
      run: |
        cd birds_nest
        pip install --upgrade pip --quiet
        python -m pip install django==5.1.3 --quiet
        python -m pip install pyecore==0.15.1 --quiet
        python -m pip install pytest==8.3.4 --quiet
        python -m pip install pytest-xdist==3.6.1 --quiet
        python -m pip install ruff==0.9.7 --quiet
        python -m pip install unidecode==1.3.8 --quiet
        python pybirdai/utils/run_tests.py --uv "False" --config-file "tests/configuration_file_tests.json"
